apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30886
